install.packages (c("tidyverse", "devtools", "readxl"))
library(devtools)
devtools::install_github("JoeyBernhardt/singer")
devtools::install_github("ropenscilabs/skimr")
devtools::install_github("nacnudus/tidyxl")
devtools::install_github("ropensci/writexl")
